version: '2.3'
services:
  # This provides the testing systemd interface
  mock-systemd:
    image: ghcr.io/balena-os/mock-systemd-bus:0.2.0
    privileged: true
    volumes:
      - dbus:/shared/dbus
    environment:
      # Set this variable with the location of your bus socket
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/shared/dbus/system_bus_socket
      # Optionally set-up any fake units you need
      MOCK_SYSTEMD_UNITS: openvpn.service dummy.service

  sut:
    build: ./
    command:
      [
        '/wait-for-it.sh',
        '--',
        'npm',
        'run',
        'test:integration',
      ]
    stop_grace_period: 3s
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/shared/dbus/system_bus_socket
    depends_on:
      - mock-systemd
    volumes:
      - dbus:/shared/dbus

volumes:
  dbus:
    driver_opts:
      # Use tmpfs to avoid files remaining between runs
      type: tmpfs
      device: tmpfs
